#!/usr/bin/env bash
pytest --nbval --ignore=intropy/_build/ \
	--ignore=intropy/solutions/assignment \
	--ignore=intropy/solutions/assignment_resit \
	--ignore=intropy/tutorials \
	--ignore=intropy/submitted \
	--ignore=intropy/autograded \
	--ignore=psychopy_test.py